name: Deploy Fibonacci Docker
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
     # - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker build -t dpoltronieri/fibonacci-docker-test -f ./client/Dockerfile.dev ./client
     # - run: docker run -e CI=true dpoltronieri/fibonacci-docker-test npm test

      - run: docker build -t dpoltronieri/multi-client ./client
      - run: docker build -t dpoltronieri/multi-nginx ./nginx
      - run: docker build -t dpoltronieri/multi-server ./server
      - run: docker build -t dpoltronieri/multi-worker ./worker

      - run: docker push dpoltronieri/multi-client
      - run: docker push dpoltronieri/multi-nginx
      - run: docker push dpoltronieri/multi-server
      - run: docker push dpoltronieri/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: fibonacci-docker
          environment_name: Fibonaccidocker-env
          existing_bucket_name: elasticbeanstalk-us-east-2-944516700047
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip